### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by acushlakoncept** [salsodworld/google-gmail-website#2]
As an aspiring developer, it's a good practice to imbibe good HTML practices.
Let the HTML validator site: https://validator.w3.org/#validate-by-upload be always there by your side to use in validating all you HTML semantics to be sure you are on track.

Your code contains about 18 HTML errors and 2 warnings.

Use the HTML validator to fix the errors.

Happy Coding 👍

**Comment by salsodev** [comment]
Thanks for the review, I have made changes to it
